import unittest
from pathlib import Path

from project_docs import read_operator_docs


class PlaylistBackendJobTests(unittest.TestCase):
    def test_playlist_download_job_can_parse_and_match_inside_backend(self):
        root = Path(__file__).resolve().parents[1]
        app_source = (root / "app.py").read_text(encoding="utf-8")
        helpers_source = (root / "helpers_mb.py").read_text(encoding="utf-8")
        jobs_routes_source = (root / "routes_jobs.py").read_text(encoding="utf-8")
        page_source = (root / "frontend" / "src" / "views" / "Playlists.tsx").read_text(encoding="utf-8")
        import_page_source = (root / "frontend" / "src" / "views" / "Import.tsx").read_text(encoding="utf-8")
        jobs_page_source = (root / "frontend" / "src" / "views" / "Jobs.tsx").read_text(encoding="utf-8")
        client_source = (root / "frontend" / "src" / "api" / "client.ts").read_text(encoding="utf-8")
        api_types_source = (root / "frontend" / "src" / "api" / "types.ts").read_text(encoding="utf-8")
        docs_source = read_operator_docs(root)

        self.assertIn('parse_content = _s(payload.get("content") or "").strip()', app_source)
        self.assertIn('"/api/playlist/parse"', app_source)
        self.assertIn('"reading playlist track list"', app_source)
        self.assertIn('state["matched_initial"] = len(matched_initial)', app_source)
        self.assertIn('active_tracks = list(parsed.get("missing") or [])', app_source)
        self.assertIn("def _playlist_download_missing_tracks", app_source)
        self.assertIn("PLAYLIST_DOWNLOAD_METHODS", app_source)
        self.assertIn("PLAYLIST_JOB_STATE_DIR", app_source)
        self.assertIn("def _playlist_job_id_for_key", app_source)
        self.assertIn("def _playlist_save_job_state", app_source)
        self.assertIn("def _playlist_interrupted_saved_job_state", app_source)
        self.assertIn("def _write_playlist_import_beets_config", app_source)
        self.assertIn("Playlist singleton", app_source)
        self.assertIn("beets-playlist-import", app_source)
        self.assertIn('"done": 0', app_source)
        self.assertIn('"failed": 0', app_source)
        self.assertIn("interrupted by an app restart", app_source)
        self.assertIn("def _playlist_write_manifest", app_source)
        self.assertIn("desired-track manifest", app_source.lower())
        self.assertIn("def _playlist_desired_tracks_for_name", app_source)
        self.assertIn("def _playlist_rows_for_saved_playlist", app_source)
        self.assertIn("desired_tracks=active_all_tracks", app_source)
        self.assertIn("Playlist Download & Sync", app_source)
        self.assertIn('"jobs_job_id"', app_source)
        self.assertIn("def _playlist_download_methods", app_source)
        self.assertIn("def _playlist_artist_looks_like_channel", app_source)
        self.assertIn("PLAYLIST_CHANNEL_ARTIST_ALIASES", app_source)
        self.assertIn("channel-alias", app_source)
        self.assertIn("def _playlist_canonicalize_track", app_source)
        self.assertIn("musicbrainz-title", app_source)
        self.assertIn("StarBoy TV", docs_source)
        self.assertIn("def _playlist_album_tag_release_placement", app_source)
        self.assertIn("album-tag-release-search", app_source)
        self.assertIn("album-tag MusicBrainz release search", docs_source)
        self.assertIn("def _playlist_slskd_download_track", app_source)
        self.assertIn("def _playlist_reusable_download_files", app_source)
        self.assertIn("Downloading missing playlist tracks via sources", app_source)
        self.assertIn("PLAYLIST_DOWNLOAD_MAX_ROUNDS", app_source)
        self.assertIn('PLAYLIST_DOWNLOAD_BATCH_SIZE = _env_int("PLAYLIST_DOWNLOAD_BATCH_SIZE", 0, minimum=0)', app_source)
        self.assertIn('batch_tracks = active_tracks[:batch_size] if batch_size > 0 else list(active_tracks)', app_source)
        self.assertIn('"download_batch_remaining": 0', app_source)
        self.assertIn("PLAYLIST_DOWNLOAD_BATCH_SIZE={batch_size}", app_source)
        self.assertIn("dl_dir = _playlist_downloads_dir(name)", app_source)
        self.assertIn("round_dl_dir = dl_dir", app_source)
        self.assertIn("batch_tracks, round_dl_dir, state, _log, download_methods", app_source)
        self.assertIn("Starting Beets singleton import from stable playlist staging", app_source)
        self.assertIn("batch_dir = _playlist_imports_dir(clean_name)", app_source)
        self.assertNotIn("active_tracks, round_dl_dir, state, _log, download_methods)", app_source)
        self.assertNotIn("round_dl_dir = dl_dir / f\"round-{round_num:02d}\"", app_source)
        self.assertNotIn("Starting Beets singleton import of {round_dl_dir}", app_source)
        self.assertIn('PLAYLIST_SLSKD_TIMEOUT", "90"', app_source)
        self.assertIn("PLAYLIST_MIN_DOWNLOAD_SECONDS", app_source)
        self.assertIn("def _audio_duration_seconds", app_source)
        self.assertIn("def _playlist_filter_preview_downloads", app_source)
        self.assertIn("def _playlist_validate_downloaded_files", app_source)
        self.assertIn("def _playlist_download_audio_allowed", app_source)
        self.assertIn("accepted fingerprint-verified download", app_source)
        self.assertIn("rejected mismatched download", app_source)
        self.assertIn("No downloaded playlist staging files are ready to import", app_source)
        self.assertIn("def _playlist_stamp_download_tags", app_source)
        self.assertIn("rejected preview-length download", app_source)
        self.assertIn("Missing-track round", app_source)
        self.assertIn("After round", app_source)
        self.assertIn("stopping missing-track loop", app_source)
        self.assertIn('"--singletons"', app_source)
        self.assertIn("Beets singleton import round", app_source)
        self.assertIn('"/api/playlists/<path:name>/tracks"', app_source)
        self.assertIn('"/api/playlists/<path:name>/resolve-track"', app_source)
        self.assertIn('"/api/playlists/<path:name>/suggestions"', app_source)
        self.assertIn('"/api/playlists/<path:name>/apply-safe-suggestions"', app_source)
        self.assertIn("def playlist_resolve_track", app_source)
        self.assertIn("def playlist_suggestions", app_source)
        self.assertIn("def playlist_apply_safe_suggestions", app_source)
        self.assertIn("def _playlist_suggestions_for_track", app_source)
        self.assertIn('def playlist_delete', app_source)
        self.assertIn('"library_tracks_deleted": 0', app_source)
        self.assertIn('"/api/playlists/quality-cleanup"', app_source)
        self.assertIn("def _playlist_quality_cleanup_candidates", app_source)
        self.assertIn("def _playlist_repair_quality_candidate", app_source)
        self.assertIn("def _playlist_move_singleton_candidate", app_source)
        self.assertIn("move_singletons", app_source)
        self.assertIn("beets-playlist-singleton-move", app_source)
        self.assertIn("def _playlist_release_looks_like_track_single", app_source)
        self.assertIn("release title", app_source)
        self.assertIn("track_title_album", app_source)
        self.assertIn("recommended_action", app_source)
        self.assertIn("delete_preview", app_source)
        self.assertIn("def _playlist_item_text_variants", app_source)
        self.assertIn("def _playlist_library_match_candidates", app_source)
        self.assertIn("def _playlist_match_payload_from_candidates", app_source)
        self.assertIn("candidates = _playlist_library_match_candidates()", app_source)
        self.assertIn('"by_title": by_title', app_source)
        self.assertIn("by_title.get(_norm(title)", app_source)
        self.assertIn("def _playlist_split_artist_title", app_source)
        self.assertIn("def _playlist_m3u_summary", app_source)
        self.assertIn("track_status_list", app_source)
        self.assertIn("checking Beets before download", app_source)
        self.assertIn("requested_only = bool(active_tracks)", app_source)
        self.assertIn("precheck_tracks = list(active_tracks if requested_only else active_all_tracks)", app_source)
        self.assertIn("Checking requested missing playlist tracks against Beets before download", app_source)
        self.assertIn("Pre-download requested-track check", app_source)
        self.assertIn('hasFreeUploadSlot', app_source)
        self.assertIn("wanted_ranked.sort(key=lambda item: (item[0], item[1], item[2], item[3]), reverse=True)", app_source)
        self.assertIn("Playlist Download & Sync: {name}", app_source)
        self.assertIn("_spotiflac_missing_tracks_download", app_source)
        self.assertIn('source="soundcloud"', app_source)
        self.assertNotIn('ytmsearch1:', app_source)
        self.assertNotIn('for prefix in ["ytmsearch1:", "ytsearch1:"]', app_source)
        self.assertIn('timeout=max(1800, min(21600, len(entries) * 240))', app_source)
        self.assertIn("PLAYLIST_AUTO_SYNC_INTERVAL", app_source)
        self.assertIn("PLAYLIST_PATH_ROOT_ALIASES", app_source)
        self.assertIn("/data/music,/music", app_source)
        self.assertIn("def _plex_machine_identifier", app_source)
        self.assertIn('"/identity"', app_source)
        self.assertIn("Plex machineIdentifier is unavailable", app_source)
        self.assertIn("def _plex_section_track_lookup", app_source)
        self.assertIn("Indexed {fetched} Plex track(s) for playlist matching", app_source)
        self.assertIn("def _playlist_sync_all", app_source)
        self.assertIn("def playlist_sync_start", app_source)
        self.assertIn("def _playlist_auto_sync_worker", app_source)
        self.assertIn("Playlist two-way sync", app_source)
        self.assertIn("require_full_plex=False", app_source)
        self.assertIn("leaving existing Plex playlist unchanged", app_source)
        self.assertIn("tracks_unmatched", app_source)
        self.assertIn("plex_synced", app_source)
        self.assertIn("local_added", app_source)
        self.assertIn("plex_added", app_source)
        self.assertIn('"/api/playlists/sync/status"', app_source)

        self.assertIn("const PLAYLIST_JOB_STORAGE_KEY", page_source)
        self.assertIn("localStorage.getItem(PLAYLIST_JOB_STORAGE_KEY)", page_source)
        self.assertIn("localStorage.setItem(PLAYLIST_JOB_STORAGE_KEY, started.job_id)", page_source)
        self.assertIn("Download Missing & Sync", page_source)
        self.assertIn("Preview Matches", page_source)
        self.assertIn("Playlist Tracks", page_source)
        self.assertIn("Available in Beets", page_source)
        self.assertIn("Missing from Beets", page_source)
        self.assertIn("View Tracks", page_source)
        self.assertIn("PlaylistJobProgress", page_source)
        self.assertIn("Previous playlist job was interrupted", page_source)
        self.assertIn("Continue Missing", page_source)
        self.assertIn("handleRetryMissingFromJob", page_source)
        self.assertIn("playlistCoverageNote", page_source)
        self.assertIn("desired_tracks?: number", api_types_source)
        self.assertIn("canonicalNote", page_source)
        self.assertIn("Download Source", page_source)
        self.assertNotIn("Playlist Quality Audit", page_source)
        self.assertNotIn("Scan Playlist Imports", page_source)
        self.assertNotIn("Place Full Songs", page_source)
        self.assertIn("track_status_list", page_source)
        self.assertIn("quality_flags", page_source)
        self.assertIn("handleSavedPlaylistPipelineAction", page_source)
        self.assertIn("handleDeletePlaylist", page_source)
        self.assertIn("handleBeginResolve", page_source)
        self.assertIn("handleSaveResolve", page_source)
        self.assertIn("handleLoadSuggestions", page_source)
        self.assertIn("handleApplySafeSuggestions", page_source)
        self.assertIn("Review Fixes", page_source)
        self.assertIn("Apply Safe Fixes", page_source)
        self.assertIn("Resolve", page_source)
        self.assertIn("Songs in Beets will not be deleted", page_source)
        self.assertIn("handleIgnoreMissing", page_source)
        self.assertIn("Run Pipeline", page_source)
        self.assertIn("Resume Pipeline", page_source)
        self.assertIn("More Actions", page_source)
        self.assertIn("Reconcile State", page_source)
        self.assertIn("Expand Log", page_source)
        self.assertEqual(page_source.count("<LogViewer"), 1)
        self.assertIn("showControls={false}", page_source)
        self.assertIn("Live log output is shown in the top pipeline bar.", page_source)
        self.assertIn("Add or Import Playlist", page_source)
        self.assertIn("aria-expanded={importExpanded}", page_source)
        self.assertIn("Show Add or Import Playlist", page_source)
        self.assertNotIn("importExpanded ? 'Collapse' : 'Open'", page_source)
        self.assertIn("Waiting Import", page_source)
        self.assertIn("Failed/Review", page_source)
        self.assertIn("playlistSyncStatusLabel", page_source)
        self.assertIn("getPlaylistDetails", page_source)
        self.assertIn("getPlaylistSyncStatus", page_source)
        self.assertIn("runPlaylistPipelineAction", page_source)
        self.assertIn("downloadRound", page_source)
        self.assertIn("downloadStatusDetail", page_source)
        self.assertNotIn("Pull, import missing, and sync?", page_source)
        self.assertIn("scoreLabel(track.score)", page_source)
        self.assertIn("source: useParsedTracks ? undefined : source", page_source)
        self.assertIn("content: useParsedTracks ? undefined : content", page_source)
        self.assertIn("methods: downloadMethod === 'auto' ? undefined : [downloadMethod]", page_source)

        self.assertIn("/api/jobs/feed", jobs_routes_source)
        self.assertIn("debug", jobs_routes_source)
        self.assertIn("Current activity", jobs_page_source)
        self.assertIn("Repair Review Rows", page_source)
        self.assertIn("album placement", page_source)
        self.assertIn("cleanupPlaylistQuality", page_source)
        self.assertNotIn("Place playlist imports", import_page_source)
        self.assertNotIn("cleanupPlaylistQuality", import_page_source)
        self.assertNotIn("Place playlist imports", jobs_page_source)
        self.assertNotIn("/api/playlists/quality-cleanup", jobs_page_source)
        self.assertIn("JobLogFeedResponse", jobs_page_source)
        self.assertIn("_albumish_penalty", helpers_source)

        self.assertIn("PlaylistDetailResponse", client_source)
        self.assertIn("PlaylistResolveTrackResponse", client_source)
        self.assertIn("PlaylistSuggestionsResponse", client_source)
        self.assertIn("PlaylistApplySuggestionsResponse", client_source)
        self.assertIn("PlaylistQualityCleanupResponse", client_source)
        self.assertIn("PlaylistDeleteResponse", client_source)
        self.assertIn("getPlaylistDetails", client_source)
        self.assertIn("resolvePlaylistTrack", client_source)
        self.assertIn("getPlaylistSuggestions", client_source)
        self.assertIn("applySafePlaylistSuggestions", client_source)
        self.assertIn("deletePlaylist", client_source)
        self.assertIn("source?: PlaylistSource;", client_source)
        self.assertIn("content?: string;", client_source)
        self.assertIn("methods?: string[];", client_source)
        self.assertIn("jobs_job_id?: string;", api_types_source)
        self.assertIn("action?: 'scan' | 'repair' | 'delete_preview' | string;", client_source)
        self.assertIn("cleanupPlaylistQuality", client_source)
        self.assertIn("getPlaylistSyncStatus", client_source)
        self.assertIn("runPlaylistPipelineAction", client_source)

        self.assertIn("complete playlist pipeline", docs_source)
        self.assertIn("avoid duplicate downloads/imports/Plex entries", docs_source)
        self.assertIn("additions can still merge both ways", docs_source)
        self.assertIn("persistent removed/excluded tombstones", docs_source)
        self.assertIn("resumable checkpoints", docs_source)
        self.assertIn("JobStore-backed and visible in Jobs", docs_source)
        self.assertIn("playlist-specific stage controls", docs_source)
        self.assertIn("70% confidence", docs_source)
        self.assertIn("Staged-file deletion must be root-checked", docs_source)
        self.assertIn("move_singletons", docs_source)
        self.assertIn("desired tracklist", docs_source)
        self.assertIn("manually resolved", docs_source)
        self.assertIn("safe suggestions", docs_source)


if __name__ == "__main__":
    unittest.main()

